# Generated by Django 4.1.1 on 2022-10-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=355, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('imageUrl', models.URLField(blank=True, null=True)),
                ('optionName', models.CharField(blank=True, max_length=355, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('prepaymentPercent', models.IntegerField(blank=True, null=True)),
                ('hideBuyBtn', models.BooleanField(default=False)),
                ('bonusesPercent', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
