# Generated by Django 4.1.1 on 2022-10-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='bonusesPercent',
        ),
        migrations.RemoveField(
            model_name='center',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='center',
            name='hideBuyBtn',
        ),
        migrations.RemoveField(
            model_name='center',
            name='optionName',
        ),
        migrations.RemoveField(
            model_name='center',
            name='prepaymentPercent',
        ),
        migrations.RemoveField(
            model_name='center',
            name='weight',
        ),
    ]
