# Generated by Django 4.1.1 on 2022-10-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_remove_center_bonusespercent_remove_center_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='optionName',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
