# Generated by Django 4.1.1 on 2022-10-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_center_optionname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='imageUrl',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
