# Generated by Django 4.1.1 on 2022-10-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_alter_center_imageurl_alter_center_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='imageUrl',
            field=models.URLField(blank=True, max_length=355, null=True),
        ),
    ]
