# Generated by Django 4.1.1 on 2022-10-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_alter_center_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='imageUrl',
            field=models.TextField(blank=True, max_length=355, null=True),
        ),
    ]
