# Generated by Django 4.1.1 on 2022-10-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_alter_center_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
