# Generated by Django 4.1.1 on 2022-10-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0007_alter_center_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='optionName',
        ),
    ]
