# Generated by Django 4.1.2 on 2022-10-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0009_center_bonusespercent_center_hidden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='bonusesPercent',
        ),
        migrations.RemoveField(
            model_name='center',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='center',
            name='hideBuyBtn',
        ),
        migrations.RemoveField(
            model_name='center',
            name='optionName',
        ),
        migrations.RemoveField(
            model_name='center',
            name='prepaymentPercent',
        ),
        migrations.RemoveField(
            model_name='center',
            name='weight',
        ),
        migrations.AlterField(
            model_name='center',
            name='imageUrl',
            field=models.URLField(blank=True, max_length=355, null=True),
        ),
    ]
