# Generated by Django 4.1.2 on 2022-10-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0010_remove_center_bonusespercent_remove_center_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='bonusesPercent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='hidden',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='hideBuyBtn',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='optionName',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='prepaymentPercent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
